version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/13th-4team-backend

permissions:
  - object: /home/ec2-user/13th-4team-backend
    # mode: 755
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/deploy-before.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/deploy-run.sh
      runas: ec2-user
      timeout: 300
